networks:
  traefik_network:
    name: traefik_network
    external: true

services:
  api:
    image: ghcr.io/heigvd-s3-dai/purrchase:latest
    container_name: purrchase-api
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      #Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      #Middlewares
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
      #Routers
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`${TRAEFIK_ROOT_FULLY_QUALIFIED_DOMAIN_NAME}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.middlewares=api-stripprefix
      #Sticky Session
      - traefik.http.services.api.loadbalancer.sticky=true
      - traefik.http.services.api.loadbalancer.sticky.cookie.name=userSession
      - traefik.http.services.api.loadbalancer.sticky.cookie.httpOnly=true
