networks:
  traefik_network:
    name: traefik_network

services:
    api:
      build:
        context: .
      container_name: purrchase-api
      networks:
        - traefik_network
      ports:
        - "8080:8080"
      labels:
        #Traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_network
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.rule=PathPrefix(`/api`)
        #Sticky Session
        - traefik.http.services.api.loadbalancer.sticky=true
        - traefik.http.services.api.loadbalancer.sticky.cookie.name=user